#!/usr/bin/env bash

opt=${1:-list}

if [ "$opt" == "list" ]; then
  dirs=$(ls /usr/local/bin/Nextion)
  for x in ${dirs[*]}; do
    if [ -d /usr/local/bin/Nextion/${x} ]; then
       tfts=$(basename -a $(ls /usr/local/bin/Nextion/${x}/*.tft))
       for y in ${tfts[*]}; do
          echo ${x}: ${y}
       done
    fi
  done
  exit 0
fi

x=$1
p1=${x/: [a-zA-Z0-9.]*/}                                       # dir
p2=${x/[a-zA-Z0-9.]*: /}                                       # tft file
p3=$(echo ${p2} | sed -n 's/.*\(NX[0-9]*[TK][0-9]*\).*/\1/p')  # model
px="/usr/local/bin/Nextion/$p1/$p2"
logger -t "[$$]" "Pi-Star --> ${px} - ${p3}"
/usr/local/bin/Nextion/nextion-upload.py ${px} /dev/ttyUSB0 ${p3} # {NX3224T024}

#sudo systemctl restart NextionDriver.service

